version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://user:password@db/donora
      - SECRET_KEY=your_secret_key
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donora
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
